### ISSUE TITLE
Mission upgrading suggestion

### ISSUE THREAD

**Issue by 1im** [10Dozen/tSF_Installer#9]
Greetings, I would like to suggest to streamline mission upgrade process slightly by << pushing the contents of the old files to the fresh framework install, as of now the mission folder is getting cluttered with .old files, which makes it less convenient

To clarify:

let's say that the upgrade will affect only settings, briefing, zones, kits and gat

1. move all old files to the /old/ folder
2. get all the new files into mission folder,
3. << "/*" add start of comment in the EOF in new Settings.sqf
4. << add contents of the old Settings.sqf file into EOF of new Settings.sqf
5. << "*/" add end of comment in the EOF in new Settings.sqf

so in the end instead of having to copy/paste contents of the files across 2 viewports, the end user will only uncomment/copy parts that he needs right in the file he edits

**Comment by 10Dozen** [comment]
Спасибо за ваше предложение, но нихуя.

1) Крутить вперед-назад большой файл так же неудобно и как открыть второй файл во вьюпорте (последнее даже удобнее, т.к. позволяет сравнивать построчно). Скачай себе WinMerge и спокойно сравнивай и переноси сеттинги в двух вьюпортах с подсветкой отличий.
2)
>   instead of having to copy/paste contents
Большинство настроек в Settings.sqf имеют дискретные значения, какой контент вы собираетесь копировать?
Gear/Dynai файлы в общем случае требуют или замены файла на предыдущий, или полную переделку, в обоих случаях удобнее хранить бекапнутый файл отдельно.

3) Файлы .old создаются только тогда, когда файлы не идентичны; а отличия могут быть как из-за пользовательских настроек, так и из-за разных версий. В большинстве модулей используются дефолтные настройки, как следствие при обновлении старых миссий будет бессмысленно дублироваться содержимое файлов + щепотка изменений и каждый нужно будет открыть, сверить с двух концов и удалить часть текста внутри файла.

**Comment by 1im** [comment]
> Скачай себе WinMerge и спокойно сравнивай и переноси сеттинги в двух вьюпортах с подсветкой отличий.

thanks, will try
